import { Transacao } from '@/types/finance';

export const MOCK_TRANSACOES: Transacao[] = [
  {
    id: '1',
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    descricao: 'Burger King',
    valor: 47.30,
    tipo: 'SAIDA_PAGA',
    categoria: 'Alimentação',
    forma_pagamento: 'DEBITO',
    observacao: 'Bk 47,30 sendo que 19 o Kajan passou',
    data_transacao: '2026-09-01',
    data_vencimento: null,
  },
  {
    id: '2',
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    descricao: 'Venda 2 Wheys',
    valor: 178.00,
    tipo: 'ENTRADA',
    categoria: 'Vendas / Renda Extra',
    forma_pagamento: 'PIX',
    observacao: 'Vendi 2 whey por 178 no pix',
    data_transacao: '2026-09-01',
    data_vencimento: null,
  },
  {
    id: '3',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    descricao: 'Fatura Nubank',
    valor: 1450.80,
    tipo: 'SAIDA_PENDENTE',
    categoria: 'Cartão de Crédito',
    forma_pagamento: 'CREDITO',
    observacao: 'Fatura fechamento setembro',
    data_transacao: '2026-08-31',
    data_vencimento: '2026-09-10',
  },
  {
    id: '4',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    descricao: 'Supermercado Carrefour',
    valor: 342.15,
    tipo: 'SAIDA_PAGA',
    categoria: 'Mercado',
    forma_pagamento: 'PIX',
    observacao: 'Compras da semana',
    data_transacao: '2026-08-30',
    data_vencimento: null,
  },
  {
    id: '5',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    descricao: 'Salário / Pro-labore',
    valor: 5500.00,
    tipo: 'ENTRADA',
    categoria: 'Salário',
    forma_pagamento: 'PIX',
    observacao: 'Depósito mensal',
    data_transacao: '2026-08-28',
    data_vencimento: null,
  },
  {
    id: '6',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    descricao: 'Conta de Energia (Enel)',
    valor: 184.50,
    tipo: 'SAIDA_PENDENTE',
    categoria: 'Moradia',
    forma_pagamento: 'PIX',
    observacao: 'Vence dia 08',
    data_transacao: '2026-08-27',
    data_vencimento: '2026-09-08',
  },
  {
    id: '7',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    descricao: 'Posto Shell Gasolina',
    valor: 120.00,
    tipo: 'SAIDA_PAGA',
    categoria: 'Transporte',
    forma_pagamento: 'DEBITO',
    observacao: 'Abastecimento',
    data_transacao: '2026-08-26',
    data_vencimento: null,
  },
];
